lib/contentful_model/base.rb

Object.const_get doesn't support getting constants within namespaces (e.g. Blog::Post) so use ActiveSupport's #constantize method instead.

Allow mapping namespaced classes

---

README.md

Shouldn't this be ```self.content_type_id```?

Typo in readme?

---

README.md

belongs_to_many example has inverse_of, missing the semi-colon

update README added missing ':' for inverse_of

---

README.md
lib/contentful_model/chainable_queries.rb
spec/chainable_queries_spec.rb

Add method for the `include` API parameter, which specifies the number of levels to fetch linked items for. [API documentation](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/retrieval-of-linked-items/query-entries)
The method couldn't be called `include` because it collided with another object's method name.

🚩 Add method for `include` API parameter

---

README.md
lib/contentful_model/chainable_queries.rb
spec/chainable_queries_spec.rb

Noticed there was a TODO for this after submitting #38 so thought I'd give it a go 😎
Creates a `params` chainable query method which can be passed an object of parameters to pass to the contentful API call.

🚩 Allow arbitrary queries against the Contentful API

---

lib/contentful_model/chainable_queries.rb
spec/chainable_queries_spec.rb

According to [Contentful Delivery API docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/order) we can sort by sys properties as well as field names: 
```
Both the sys properties (such as sys.createdAt) or field values (such as fields.myCustomDateField) can be used for ordering.
```
The current `.order()` method only implements the `order` query hash with "fields".  As a workaround, we're currently the `params(order: '-sys.updatedAt')` to get us where we need to go, but would like to just user the order method as we are elsewhere.
I've updated the `order()` to check the incoming field name against the known keys from `Contentful::Resource::SystemProperties:: SYS_COERCIONS` and use "sys" when matching that key.  I'm not sure if …

Updating .order() to also accept sys properties

---

lib/contentful_model/associations/has_many.rb
lib/contentful_model/associations/has_one.rb

Currently, the has_one and has_many associations will attempt to fetch the associated fields in this order:
1.  With `super()` - sent to `method_missing` in base.rb and tries to get field.  If can't find, throws AttributeNotFoundError exception (rescued by 2 below)
2.  If rescued from AttributeNotFoundError and the `association_name` != class name, then tries using the class name by doing `.send(options[:class_name].pluralize.underscore.to_sym)`.  This also ends up in `method_missing` and can throw another AttributeNotFoundError exception (not caught because already in rescue block).
3.  If `association_name` == class name, then gives up and returns either nil (for has_one) or [](for has_many)
This causes issues because the Contentful Delivery API simply doesn't include a field at all in …

has_many, has_one - Preventing further 'AttributeNotFoundError' exception in rescue

---

lib/contentful_model/base.rb
spec/base_spec.rb

This fixes a bug where using our models with Action Views `#cache` wouldn't work as expected – i.e. cache key wouldn't actually include the updated timestamp – using Rails's `[ActiveSupport::Cache::FileStore]` & `watch` was a good way to see this in action.
This is because by default if the object doesn't `#respond_to?(:cache_key)` Rails only calls `#to_s` – assuming it's just a PORO:
```
> ActiveSupport::Cache.expand_cache_key([OpenStruct.new])
=> "#<OpenStruct>"
> ActiveSupport::Cache.expand_cache_key([Struct.new(:to_param).new('ID')])
=> "ID"
> ActiveSupport::Cache.expand_cache_key([Struct.new(:cache_key).new('KEY')])
=> "KEY"
> ActiveSupport::Cache.expand_cache_key([Struct.new(:cache_key) { private(:cache_key, :to_a) }.new('KEY')])
=> "#<struct cache_key=\"KEY\">"
```
For the cache …

Make our version of #cache_key public

---

lib/contentful_model/base.rb
spec/base_spec.rb
spec/spec_helper.rb

This puts the use defined coercions between the user and field data at all points in our API – historically we only coercing field values that are accessed via `#method_missing`.

Coerce values that pass through our getters

---

lib/contentful_model/associations/has_many.rb
lib/contentful_model/associations/has_one.rb

Might be a little off base here, but I noticed an issue with the has_many & has_one class methods.  Specifically an issue when the associated model does not have an inverse association set up.
Changes for both:
* I don't think it's required to have the inverse association set up on the child model and use the "inverse_of" keyword.  Therefore, I'm adding a check to ensure that the child responds to the inverse setter before attempting.  Previously, even if the call to super() here works, the `child.send()` could throw an AttributeNotFoundError exception and cause this to jump into the rescue.  This method would then return an empty array even though the `super()` correctly returned an array of associated objects.
Other change for has_many:
* I don't _think_ we want this method to return …

Fix for has_many/has_one association(?)

---

lib/contentful_model/query.rb

Not sure if this is the best approach, but I noticed that ContentfulModel is returning all results as instance of `Array` instead of `Contentful::Array`.  Because of this, we lose access to some of the pagination methods that come from `Contentful::Array` (`total`, `next_page`, etc).  Looks like that's because of both the `to_a` and `reject` here being called straight on the `result` object.
My recommendation here is to simply call the `reject!` on the items within the results.  This will allow `execute` to return a Contentful::Array.  I think this is a small step in the right direction, however there are still problems with this code.  Mainly that if items are rejected, the `result.total` will no reflect the lose of the item(s).  Though that value is coming straight from the API.  So …

Updating query#execute to call `reject!` on result.items

---

lib/contentful_model/base.rb
lib/contentful_model/validations/validates_presence_of.rb

This validator currently only checks if the instance can `respond_to?` the noted field, which is always true if you have declared the field as a has_one, has_many, or return_nil_for_empty.
* Updating validates_presence_of to check `.present?` in addition to `respond_to?`
* Had to rescue the `.send(field)` as it could return `ContentfulModel::AttributeNotFoundError` even if declared in has_one, has_many, or return_nil_for_empty.
* Also fixing issue with crucial `method_missing`, where it attempts to filter out "invalid" entries from being returned.  The `reject` condition was running against `respond_to?(:invalid)` but should be checking `respond_to?(:invalid)`

Potential fix for PresenceValidation

---

README.md

It took me a little while to work out why all my fields had no content, this documents the reason why.

Add `default_locale` details to readme

---

lib/contentful_model/migrations/migration.rb
spec/migrations/migration_spec.rb

Makes `add_content_type_field` behave similarly to `create_content_type`, i.e., allows a block to passed, which is useful for adding things, e.g., validations.

Add content type field with block

---

README.md

The coercions to `Date` and `Integer` are documented wrongly in the README. This PR corrects that & adds a link to all the available coercions.

Correct coercion type and add a link to list

---

lib/contentful_model/migrations/content_type.rb
spec/migrations/content_type_spec.rb

Currently, there is no way to specify displayField for a content type.
This PR adds that ability
```ruby
create_content_type 'StaticPage' do |ct|
ct.display_field = 'title'
ct.field 'title', :string
ct.field 'slug', :string
end
```

Allow to specify display field during migration

---

lib/contentful_model/migrations/content_type.rb
spec/migrations/content_type_spec.rb

Currently, there is no way to define a rich_text field via migration.
This PR adds support for that
```ruby
class CreateFooContentType < ActiveRecord::Migration
include ContentfulModel::Migrations::Migration
def up
create_content_type('foo') do |ct|
ct.field('bar', :rich_text)
end
end
def down
end
end
```

Add support for rich_text field

---

lib/contentful_model/migrations/content_type.rb
spec/migrations/content_type_spec.rb

ContentfulModel::Migrations::ContentType.remove_field does not update
the memoized @fields array on `remove_field`. Calling `save` on the
instance after removing the field causes an exception to be raised.

Fix exception on Migration.remove_content_type_field

---

lib/contentful_model/migrations/content_type.rb
spec/migrations/content_type_spec.rb

Currently, `contenful_model` migrations API allows only `entry_array` and `asset_array` types.
This PR adds support for `symbol_array` - basically a list of symbol items

Add support for symbol_array type

---

lib/contentful_model.rb
lib/contentful_model/manageable.rb
lib/contentful_model/management.rb

Some of the configuration values are being lost because `ContentfulModel::Management` is created without the configured values in some locations. `ContentfulModel::Migrations::ContentTypeFactory.find`, for example, creates an instance of `ContentfulModel::Management` with no configuration.
This change centralises the configuration into `ContentfulModel::Management.initialize` so that all instances use the configured values, such as `default_locale`.
Losing `default_locale` causes errors when a space is configured without the default `en-US` locale.

Fix loss of configured default_locale

---

lib/contentful_model/migrations/content_type.rb
spec/migrations/content_type_spec.rb

This is a follow-up PR for this one https://github.com/contentful/contentful_model/pull/133
Unfortunately, there are still issues with the `#remove_field` method.
`#remove_field` calls `@management_content_type.fields.destroy(field_id)` under the hood, that in turn [calls `update(fields: fields)`. ](https://github.com/contentful/contentful-management.rb/blob/master/lib/contentful/management/content_type.rb#L118)
But `fields` is set here https://github.com/contentful/contentful_model/blob/master/lib/contentful_model/migrations/content_type.rb#L31, but at the same time it gets modified here https://github.com/contentful/contentful-management.rb/blob/master/lib/contentful/management/content_type.rb#L159 so, in the end, the `@fields` instanсe variable contains the modified data that …

Refresh fields after #remove_field call

---

README.md

This is a really cool gem! I went ahead and made some minor Markdown tweaks to enable syntax highlighting for all of the code examples.

Add syntax highlighting to readme code examples

---

lib/contentful_model/errors.rb
lib/contentful_model/queries.rb
lib/contentful_model/query.rb
spec/query_spec.rb

This PR adds `load!` method that raises an exception(`ContentfulModel::NotFoundError`) when a response is blank(either `nil` or an empty array)
It mirrors Rails bang/non-bang approach

Add load! method

---

README.md

Related: #53
> I've changed my mind and think that the eager-loading mechanism belongs into the Rails::Engine as it's part of the Rails configuration pattern
I found that entry mapping could return wrong classes when using associations, and contentful_model will not support auto eager-loading for now.
However, since contenful_rails is still work in progress, some people (including me) are using contentful_model directly from Rails. So it seems that adding tips (instead of feature) for eager-loading may help avoiding pitfalls.

Doc: Write about add_entry_mapping

---

lib/contentful_model/base.rb
lib/contentful_model/manageable.rb

Fixes https://github.com/contentful/contentful_model/issues/140

add dynamic setter for empty fields
